# Generated by Django 5.1.5 on 2025-02-05 02:43

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_flag_media_save_upvote'),
    ]

    operations = [
         migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
