# Generated by Django 5.1.5 on 2025-02-12 17:12

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_comment_user_alter_flag_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[posts.models.validate_file_size]),
        ),
    ]
